---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  ansible_host_key_checking: false

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 600

    - name: "install python for Ansible."
      become: true
      raw: apt install -y python3
      changed_when: false

  roles:
    - configure-server
    - configure-prometheus-node-exporter