---
- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: "Copy backend tar.gz file and unzipping it"
  become: yes
  unarchive:
    src: ~/project/backend.tar.gz
    dest: /home/ubuntu

- name: "Build artifact and run migrations"
  become: yes
  shell: |
    npm audit fix
    npm run build
    npm run migrations
  npm:
    path: /home/ubuntu/backend

- name: "Start pm2"
  become: yes
  shell: |
    pm2 start npm --name backend -- start
  npm:
    path: /home/ubuntu/backend/.dist
