---
- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: "copy backend tar.gz file and unzipping it"
  become: yes
  unarchive:
    src: ~/project/backend.tar.gz
    dest: /home/ubuntu

- name: "Build artifact"
  become: yes
  shell: |
    cd backend
    npm install
    npm run migrations
    pm2 start --name "backend" npm -- start
